In [1]:
import pandas as pd
import numpy as np
import time
import random

In [2]:
from datetime import datetime, timedelta

In [3]:
full_set = pd.read_json('full_set.json')

In [4]:
full_set = full_set.dropna(how='any')

In [8]:
full_set.sort_values(by = 'Date',inplace = True)

In [11]:
full_set.set_index(full_set.Date,inplace = True)

In [12]:
full_set

,10d_p,Close,Date,Volume,exp_senti,exp_senti_std
Date,,,,,,
2015-01-01,265.66,314.25,2015-01-01,8036550,0.931250,1.946381
2015-01-02,267.80,315.03,2015-01-02,7860650,0.010345,2.320574
2015-01-03,225.86,281.08,2015-01-03,33054400,1.302632,2.544187
2015-01-04,178.10,264.20,2015-01-04,55629100,-0.075758,0.869702
2015-01-05,209.84,274.47,2015-01-05,43962800,0.215385,2.234639
2015-01-06,208.10,286.19,2015-01-06,23245700,0.126471,1.183790
2015-01-07,199.26,294.34,2015-01-07,24866800,0.751613,2.462214
2015-01-08,210.34,283.35,2015-01-08,19982500,0.387097,1.753106
2015-01-09,214.86,290.41,2015-01-09,18718600,64.248151,322.822413
2015-01-10,211.32,274.80,2015-01-10,15264300,-0.220690,0.950999
2015-01-11,226.90,265.66,2015-01-11,18200800,1.208824,3.569426
2015-01-12,233.41,267.80,2015-01-12,18880300,0.624138,1.979665
2015-01-13,232.88,225.86,2015-01-13,72843900,0.193939,3.360009
2015-01-16,273.47,208.10,2015-01-16,38421000,0.526667,1.539033
2015-01-17,263.48,199.26,2015-01-17,23469700,0.432258,6.819156
2015-01-18,233.92,210.34,2015-01-18,30085100,0.618750,1.811843
2015-01-19,233.51,214.86,2015-01-19,18658300,1.412500,2.521625
2015-01-20,226.43,211.32,2015-01-20,24051100,0.380769,2.118602
2015-01-21,217.46,226.90,2015-01-21,29924600,0.397059,2.067036
2015-01-22,226.97,233.41,2015-01-22,33544600,0.846667,1.830070
2015-01-23,238.23,232.88,2015-01-23,24621700,1.650000,2.190548
2015-01-24,227.27,247.85,2015-01-24,24782500,0.427778,1.021331
2015-01-25,226.85,253.72,2015-01-25,33582700,0.500000,2.177289
2015-01-26,217.11,273.47,2015-01-26,106794000,-0.200000,1.438518
2015-01-27,222.27,263.48,2015-01-27,44399000,1.108571,3.479357
2015-01-28,227.75,233.92,2015-01-28,44352200,0.700000,1.180728
2015-01-29,223.41,233.51,2015-01-29,32213400,1.989655,4.164989
2015-01-30,220.11,226.43,2015-01-30,26605200,0.521622,2.170457
2015-01-31,219.84,217.46,2015-01-31,23348200,0.896296,2.831893
2015-02-01,219.19,226.97,2015-02-01,29128500,-0.025000,0.119896
...,...,...,...,...,...,...
2017-12-01,16936.80,10975.60,2017-12-01,6783120000,4.602632,27.120467
2017-12-02,17415.40,11074.60,2017-12-02,5138500000,15.773846,96.473365
2017-12-03,16408.20,11323.20,2017-12-03,6608310000,26.384848,95.931173
2017-12-04,16564.00,11657.20,2017-12-04,6132410000,12.698781,53.732635
2017-12-05,17706.90,11916.70,2017-12-05,6895260000,86.502706,482.714962
2017-12-06,19497.40,14291.50,2017-12-06,12656300000,13.512329,44.968649
2017-12-07,19140.80,17899.70,2017-12-07,17950700000,20.329546,62.946914
2017-12-08,19114.20,16569.40,2017-12-08,21136000000,22.069412,98.827596
2017-12-09,17776.70,15178.20,2017-12-09,13911300000,19.080392,79.817822
2017-12-10,16624.60,15455.40,2017-12-10,13433300000,55.774667,252.134041
2017-12-11,15802.90,16936.80,2017-12-11,12153900000,21.502702,89.444873
2017-12-12,13831.80,17415.40,2017-12-12,14603800000,30.129214,98.407590
2017-12-13,14699.20,16408.20,2017-12-13,12976900000,-2.236735,18.714468
2017-12-14,13925.80,16564.00,2017-12-14,13777400000,19.569334,84.249519
2017-12-15,14026.60,17706.90,2017-12-15,14310000000,-0.943750,34.515214
2017-12-16,16099.80,19497.40,2017-12-16,12740600000,8.808065,62.256924
2017-12-17,15838.50,19140.80,2017-12-17,13314600000,20.902326,56.993832
2017-12-18,14606.50,19114.20,2017-12-18,14839500000,23.343679,69.425697
2017-12-19,14656.20,17776.70,2017-12-19,16894500000,4.971795,18.937942
2017-12-20,12952.20,16624.60,2017-12-20,22149700000,8.951042,70.095823
2017-12-21,14156.40,15802.90,2017-12-21,16516600000,6.414894,50.421935
2017-12-22,13657.20,13831.80,2017-12-22,22198000000,29.580809,123.906455
2017-12-23,14982.10,14699.20,2017-12-23,13086000000,-1.532609,28.378759
2017-12-24,15201.00,13925.80,2017-12-24,11572300000,19.513637,42.886623
2017-12-25,15599.20,14026.60,2017-12-25,10664700000,-3.555556,19.809993
2017-12-26,17429.50,16099.80,2017-12-26,13454300000,62.786154,182.105848
2017-12-27,17527.00,15838.50,2017-12-27,12487600000,16.760976,60.624772
2017-12-28,16477.60,14606.50,2017-12-28,12336500000,23.983334,70.350941
2017-12-29,15170.10,14656.20,2017-12-29,13025500000,13.806818,55.667685
2017-12-30,14595.40,12952.20,2017-12-30,14452600000,25.534286,105.103780

In [13]:
test_set = full_set.loc[(datetime(2015,10,1)):(datetime(2015,12,1)),:].append(full_set.loc[(datetime(2016,10,1)):(datetime(2016,12,1)),:]).append(full_set.loc[(datetime(2017,10,1)):(datetime(2017,12,1)),:])

In [14]:
test_set

,10d_p,Close,Date,Volume,exp_senti,exp_senti_std
Date,,,,,,
2015-10-01,247.05,237.55,2015-10-01,20488800,2.377778,11.083633
2015-10-02,245.31,237.29,2015-10-02,19677900,1.818919,6.056841
2015-10-03,249.51,238.73,2015-10-03,16482700,0.204545,0.515644
2015-10-04,251.99,238.26,2015-10-04,12999000,1.288235,2.580785
2015-10-05,254.32,240.38,2015-10-05,23335900,0.346154,3.485269
2015-10-06,262.87,246.06,2015-10-06,27535100,5.910811,29.160115
2015-10-07,270.64,242.97,2015-10-07,22999200,0.200000,1.197805
2015-10-08,261.64,242.30,2015-10-08,18515300,0.351351,3.630846
2015-10-09,263.44,243.93,2015-10-09,17353100,-0.287500,1.423409
2015-10-10,269.46,244.94,2015-10-10,15912700,5.575000,7.961902
2015-10-11,266.27,247.05,2015-10-11,16827300,-2.386667,14.147738
2015-10-12,274.02,245.31,2015-10-12,17388300,0.922857,2.683078
2015-10-13,276.50,249.51,2015-10-13,28198500,0.430435,1.619832
2015-10-14,281.65,251.99,2015-10-14,27462600,0.942500,2.392894
2015-10-15,283.68,254.32,2015-10-15,25223500,0.260000,0.554737
2015-10-16,285.30,262.87,2015-10-16,35901500,2.741667,5.729571
2015-10-17,293.79,270.64,2015-10-17,43199600,0.280952,2.215663
2015-10-18,304.62,261.64,2015-10-18,22434300,0.641667,2.704048
2015-10-19,313.86,263.44,2015-10-19,25258800,-0.228571,0.905088
2015-10-20,328.02,269.46,2015-10-20,30889800,0.671795,2.029014
2015-10-21,314.17,266.27,2015-10-21,25637300,0.143478,1.474073
2015-10-22,325.43,274.02,2015-10-22,37808600,1.350000,2.343964
2015-10-23,361.19,276.50,2015-10-23,29442500,0.181481,1.160472
2015-10-24,403.42,281.65,2015-10-24,25942400,1.141935,2.777301
2015-10-25,411.56,283.68,2015-10-25,45717100,0.103448,0.535294
2015-10-26,386.35,285.30,2015-10-26,32108800,0.742857,2.039087
2015-10-27,374.47,293.79,2015-10-27,46331800,0.588889,1.660786
2015-10-28,386.48,304.62,2015-10-28,50808100,0.973684,2.321488
2015-10-29,373.37,313.86,2015-10-29,64495900,0.195833,0.805439
2015-10-30,380.26,328.02,2015-10-30,78305000,9.758824,56.738146
...,...,...,...,...,...,...
2017-11-02,5950.07,7078.50,2017-11-02,4653770000,9.111865,44.700602
2017-11-03,6559.49,7207.76,2017-11-03,3369860000,20.103126,67.715766
2017-11-04,6635.75,7379.95,2017-11-04,2483800000,26.284782,108.801894
2017-11-05,7315.54,7407.41,2017-11-05,2380410000,2.317500,6.037462
2017-11-06,7871.69,7022.76,2017-11-06,3111900000,12.528261,59.085755
2017-11-07,7708.99,7144.38,2017-11-07,2326340000,3.287500,12.308842
2017-11-08,7790.15,7459.69,2017-11-08,4602200000,6.964616,123.732874
2017-11-09,8036.49,7143.58,2017-11-09,3226250000,28.735714,175.726886
2017-11-10,8200.64,6618.14,2017-11-10,5208250000,19.307018,61.225777
2017-11-11,8071.26,6357.60,2017-11-11,4908680000,19.238636,79.203641
2017-11-12,8253.55,5950.07,2017-11-12,8957350000,3.144068,28.422110
2017-11-13,8038.77,6559.49,2017-11-13,6263250000,0.615789,2.969098
2017-11-14,8253.69,6635.75,2017-11-14,3197110000,13.990909,53.066941
2017-11-15,8790.92,7315.54,2017-11-15,4200880000,0.400000,9.329349
2017-11-16,9330.55,7871.69,2017-11-16,5123810000,11.306451,95.166795
2017-11-17,9818.35,7708.99,2017-11-17,4651670000,29.305555,121.448688
2017-11-18,10058.80,7790.15,2017-11-18,3667190000,10.343104,24.761519
2017-11-19,9888.61,8036.49,2017-11-19,3149320000,18.344000,123.145832
2017-11-20,10233.60,8200.64,2017-11-20,3488450000,15.790477,51.633086
2017-11-21,10975.60,8071.26,2017-11-21,4277610000,11.387500,51.196806
2017-11-22,11074.60,8253.55,2017-11-22,3633530000,20.113637,67.213784
2017-11-23,11323.20,8038.77,2017-11-23,4225180000,5.228261,16.549552
2017-11-24,11657.20,8253.69,2017-11-24,5058610000,73.477776,476.628614
2017-11-25,11916.70,8790.92,2017-11-25,4342060000,7.860000,17.900297
2017-11-26,14291.50,9330.55,2017-11-26,5475580000,-4.571698,55.828911
2017-11-27,17899.70,9818.35,2017-11-27,5653320000,28.570271,105.518492
2017-11-28,16569.40,10058.80,2017-11-28,6348820000,83.666102,241.226849
2017-11-29,15178.20,9888.61,2017-11-29,11568800000,0.075676,11.022959
2017-11-30,15455.40,10233.60,2017-11-30,8310690000,11.607576,59.681632
2017-12-01,16936.80,10975.60,2017-12-01,6783120000,4.602632,27.120467

In [15]:
train_set = full_set.drop(test_set.index)

In [16]:
train_set

,10d_p,Close,Date,Volume,exp_senti,exp_senti_std
Date,,,,,,
2015-01-01,265.66,314.25,2015-01-01,8036550,0.931250,1.946381
2015-01-02,267.80,315.03,2015-01-02,7860650,0.010345,2.320574
2015-01-03,225.86,281.08,2015-01-03,33054400,1.302632,2.544187
2015-01-04,178.10,264.20,2015-01-04,55629100,-0.075758,0.869702
2015-01-05,209.84,274.47,2015-01-05,43962800,0.215385,2.234639
2015-01-06,208.10,286.19,2015-01-06,23245700,0.126471,1.183790
2015-01-07,199.26,294.34,2015-01-07,24866800,0.751613,2.462214
2015-01-08,210.34,283.35,2015-01-08,19982500,0.387097,1.753106
2015-01-09,214.86,290.41,2015-01-09,18718600,64.248151,322.822413
2015-01-10,211.32,274.80,2015-01-10,15264300,-0.220690,0.950999
2015-01-11,226.90,265.66,2015-01-11,18200800,1.208824,3.569426
2015-01-12,233.41,267.80,2015-01-12,18880300,0.624138,1.979665
2015-01-13,232.88,225.86,2015-01-13,72843900,0.193939,3.360009
2015-01-16,273.47,208.10,2015-01-16,38421000,0.526667,1.539033
2015-01-17,263.48,199.26,2015-01-17,23469700,0.432258,6.819156
2015-01-18,233.92,210.34,2015-01-18,30085100,0.618750,1.811843
2015-01-19,233.51,214.86,2015-01-19,18658300,1.412500,2.521625
2015-01-20,226.43,211.32,2015-01-20,24051100,0.380769,2.118602
2015-01-21,217.46,226.90,2015-01-21,29924600,0.397059,2.067036
2015-01-22,226.97,233.41,2015-01-22,33544600,0.846667,1.830070
2015-01-23,238.23,232.88,2015-01-23,24621700,1.650000,2.190548
2015-01-24,227.27,247.85,2015-01-24,24782500,0.427778,1.021331
2015-01-25,226.85,253.72,2015-01-25,33582700,0.500000,2.177289
2015-01-26,217.11,273.47,2015-01-26,106794000,-0.200000,1.438518
2015-01-27,222.27,263.48,2015-01-27,44399000,1.108571,3.479357
2015-01-28,227.75,233.92,2015-01-28,44352200,0.700000,1.180728
2015-01-29,223.41,233.51,2015-01-29,32213400,1.989655,4.164989
2015-01-30,220.11,226.43,2015-01-30,26605200,0.521622,2.170457
2015-01-31,219.84,217.46,2015-01-31,23348200,0.896296,2.831893
2015-02-01,219.19,226.97,2015-02-01,29128500,-0.025000,0.119896
...,...,...,...,...,...,...
2017-09-30,4781.99,4338.71,2017-09-30,1207450000,10.504546,45.712118
2017-12-02,17415.40,11074.60,2017-12-02,5138500000,15.773846,96.473365
2017-12-03,16408.20,11323.20,2017-12-03,6608310000,26.384848,95.931173
2017-12-04,16564.00,11657.20,2017-12-04,6132410000,12.698781,53.732635
2017-12-05,17706.90,11916.70,2017-12-05,6895260000,86.502706,482.714962
2017-12-06,19497.40,14291.50,2017-12-06,12656300000,13.512329,44.968649
2017-12-07,19140.80,17899.70,2017-12-07,17950700000,20.329546,62.946914
2017-12-08,19114.20,16569.40,2017-12-08,21136000000,22.069412,98.827596
2017-12-09,17776.70,15178.20,2017-12-09,13911300000,19.080392,79.817822
2017-12-10,16624.60,15455.40,2017-12-10,13433300000,55.774667,252.134041
2017-12-11,15802.90,16936.80,2017-12-11,12153900000,21.502702,89.444873
2017-12-12,13831.80,17415.40,2017-12-12,14603800000,30.129214,98.407590
2017-12-13,14699.20,16408.20,2017-12-13,12976900000,-2.236735,18.714468
2017-12-14,13925.80,16564.00,2017-12-14,13777400000,19.569334,84.249519
2017-12-15,14026.60,17706.90,2017-12-15,14310000000,-0.943750,34.515214
2017-12-16,16099.80,19497.40,2017-12-16,12740600000,8.808065,62.256924
2017-12-17,15838.50,19140.80,2017-12-17,13314600000,20.902326,56.993832
2017-12-18,14606.50,19114.20,2017-12-18,14839500000,23.343679,69.425697
2017-12-19,14656.20,17776.70,2017-12-19,16894500000,4.971795,18.937942
2017-12-20,12952.20,16624.60,2017-12-20,22149700000,8.951042,70.095823
2017-12-21,14156.40,15802.90,2017-12-21,16516600000,6.414894,50.421935
2017-12-22,13657.20,13831.80,2017-12-22,22198000000,29.580809,123.906455
2017-12-23,14982.10,14699.20,2017-12-23,13086000000,-1.532609,28.378759
2017-12-24,15201.00,13925.80,2017-12-24,11572300000,19.513637,42.886623
2017-12-25,15599.20,14026.60,2017-12-25,10664700000,-3.555556,19.809993
2017-12-26,17429.50,16099.80,2017-12-26,13454300000,62.786154,182.105848
2017-12-27,17527.00,15838.50,2017-12-27,12487600000,16.760976,60.624772
2017-12-28,16477.60,14606.50,2017-12-28,12336500000,23.983334,70.350941
2017-12-29,15170.10,14656.20,2017-12-29,13025500000,13.806818,55.667685
2017-12-30,14595.40,12952.20,2017-12-30,14452600000,25.534286,105.103780

In [17]:
train_target = train_set['10d_p']

In [53]:
Y = train_target.as_matrix()
X = train_predictor.as_matrix()

In [20]:
train_predictor = train_set[['exp_senti','exp_senti_std']]

In [24]:
test_target = test_set['10d_p']

In [25]:
test_predictor = test_set[['exp_senti','exp_senti_std']]

In [57]:
test_X = test_predictor.as_matrix()
test_Y = test_target.as_matrix()

In [60]:
f_X = full_set[['exp_senti','exp_senti_std']].as_matrix()
f_Y = full_set['10d_p'].as_matrix()

In [54]:
from sklearn.ensemble import RandomForestRegressor

rf_regression = RandomForestRegressor()

rf_regression.fit(X,Y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [55]:
from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_score

def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard deviation:", scores.std())

In [61]:
rfr_scores = cross_val_score(rf_regression,f_X, f_Y,
                             scoring="neg_mean_squared_error", cv=5)
display_scores(rfr_scores)

Scores: [ -3489655.46711122  -2041868.75540289  -1910725.05194297
  -5064244.94683766 -52187197.44905524]
Mean: -12938738.3341
Standard deviation: 19657533.9226

In [65]:
from sklearn.model_selection import GridSearchCV
param_grid = [
    # try 16 (4×4) combinations of hyperparameters
    {'n_estimators': [5, 20, 10, 50,100], 'max_features': ['auto', 'log2', 'sqrt']},
    # then try 12 (3×4) combinations with bootstrap set as False
    {'bootstrap': [False], 'n_estimators': [5, 10, 20,100], 'max_features': ['auto','log2', 'sqrt']},
  ]

rf_regression = RandomForestRegressor()
# train across 5 folds, we have about 700 case, split them to 5 folds should good enough
grid_search = GridSearchCV(rf_regression, param_grid, cv=5,
                           scoring='neg_mean_squared_error', return_train_score=True)
grid_search.fit(f_X, f_Y)
grid_search.best_estimator_

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='sqrt', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [66]:
rf_regression2 = RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='sqrt', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)
rf_regression2.fit(X,Y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='sqrt', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [67]:
rfr2_scores = cross_val_score(rf_regression2,f_X, f_Y,
                             scoring="neg_mean_squared_error", cv=5)
display_scores(rfr2_scores)

Scores: [ -2808382.82070681  -2108004.88468116  -1795175.72107674
  -5025568.07814645 -52597557.37245253]
Mean: -12866937.7754
Standard deviation: 19897348.0243

In [68]:
from sklearn.ensemble import GradientBoostingRegressor
GBR = GradientBoostingRegressor()
GBR.fit(X,Y)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='ls', max_depth=3, max_features=None,
             max_leaf_nodes=None, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=100, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False)

In [69]:
GBR_scores = cross_val_score(GBR,f_X, f_Y,
                             scoring="neg_mean_squared_error", cv=5)
display_scores(GBR_scores)

Scores: [ -3672937.18782877  -1639638.70745691  -1879550.86889522
  -4039632.31298067 -52427219.2152999 ]
Mean: -12731795.6585
Standard deviation: 19870331.827

In [71]:
param_grid_GBR = [
    {'loss':['ls', 'lad', 'huber', 'quantile'], 'learning_rate': [0.02,0.05, 0.1, 0.2], 'n_estimators': [50,100,200,300,400,800], 'max_features': ['log2', 'sqrt','auto']}
]

GBR = GradientBoostingRegressor()
grid_search = GridSearchCV(GBR, param_grid_GBR, cv=5,
                           scoring='neg_mean_squared_error', return_train_score=True)
grid_search.fit(X, Y)

GridSearchCV(cv=5, error_score='raise',
       estimator=GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='ls', max_depth=3, max_features=None,
             max_leaf_nodes=None, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=100, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'loss': ['ls', 'lad', 'huber', 'quantile'], 'learning_rate': [0.02, 0.05, 0.1, 0.2], 'n_estimators': [50, 100, 200, 300, 400, 800], 'max_features': ['log2', 'sqrt', 'auto']}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='neg_mean_squared_error', verbose=0)

In [74]:
GBR2 = GridSearchCV(cv=5, error_score='raise',
       estimator=GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='ls', max_depth=3, max_features=None,
             max_leaf_nodes=None, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=100, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'loss': ['ls', 'lad', 'huber', 'quantile'], 'learning_rate': [0.02, 0.05, 0.1, 0.2], 'n_estimators': [50, 100, 200, 300, 400, 800], 'max_features': ['log2', 'sqrt', 'auto']}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='neg_mean_squared_error', verbose=0)

GBR2.fit(X,Y)

GridSearchCV(cv=5, error_score='raise',
       estimator=GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='ls', max_depth=3, max_features=None,
             max_leaf_nodes=None, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=100, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'loss': ['ls', 'lad', 'huber', 'quantile'], 'learning_rate': [0.02, 0.05, 0.1, 0.2], 'n_estimators': [50, 100, 200, 300, 400, 800], 'max_features': ['log2', 'sqrt', 'auto']}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='neg_mean_squared_error', verbose=0)

In [75]:
GBR2_scores = cross_val_score(GBR2,f_X, f_Y,
                             scoring="neg_mean_squared_error", cv=5)
display_scores(GBR2_scores)

Scores: [ -1720252.11638694   -545420.42838363   -848866.37570808
  -2920225.60300247 -56084817.60374927]
Mean: -12423916.4254
Standard deviation: 21846021.6579